export enum ConfigEnum {
  ENVIRONMENT = 'ENVIRONMENT',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DBNAME = 'DATABASE_DBNAME',
}

export enum LogEnum {
  LOG_ON = 'LOG_ON',
  LOG_LEVEL = 'LOG_LEVEL',
}
